services:
  backend:
    build:
      context: .
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - "8010:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/var/www/static:ro
      - ./media:/var/www/media:ro
    depends_on:
      - backend

