services:
  frontend:
    image: node:17.6.0-bullseye-slim
    working_dir: /app
    command: sh -c "npm ci && ./node_modules/.bin/parcel watch bundles-src/index.jsx --dist-dir bundles --public-url='/static/' --no-cache"
    volumes:
      - .:/app

  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - frontend

volumes:
  media: