# Generated by Django 5.2.7 on 2025-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('in_progress', 'Готовится'), ('delivered', 'Доставлен')], default='unprocessed', max_length=20, verbose_name='Статус'),
        ),
    ]
