# Generated by Django 5.2.7 on 2025-11-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('electronic', 'Электронно')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
