# Generated by Django 5.2.9 on 2025-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longtitude',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота'),
        ),
    ]
