# Generated by Django 5.2.9 on 2025-12-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_restaurant_latitude_restaurant_longtitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
